export default {
	reg: {
		chinaPhone: /^0?(13[0-9]|14[57]|15[0-9]|166|17[0-9]|18[0-9]|19[89])[0-9]{8}$/,
		phoneCode: /^[0-9]{6}$/,
		number: /^[0-9]+$/,
		NumberTwoDecimal: /^(([1-9][0-9]*)|(([0]\.\d{1,2}|[1-9][0-9]*\.\d{1,2})))$/,
		chinaName: /^[\u4E00-\u9FA5]{2,4}$/,
		email: /^[a-zA-Z0-9_.-]+@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.[a-zA-Z0-9]{2,6}$/,
	},
	phoneCode: {
		time: 60,
		btnStartText: "获取验证码",
		btnEndText: "重新发送",
	},
	cityOptionsOne: [
		{ name: "安徽", id: 1, type: "A" },
		{ name: "北京", id: 19, type: "B" },
		{ name: "重庆", id: 532, type: "C" },
		{ name: "福建", id: 39, type: "F" },
		{ name: "甘肃", id: 52, type: "G" },
		{ name: "广东", id: 68, type: "G" },
		{ name: "广西", id: 92, type: "G" },
		{ name: "贵州", id: 109, type: "G" },
		{ name: "海南", id: 120, type: "H" },
		{ name: "河北", id: 125, type: "H" },
		{ name: "河南", id: 145, type: "H" },
		{ name: "黑龙江", id: 165, type: "H" },
		{ name: "湖北", id: 184, type: "H" },
		{ name: "湖南", id: 212, type: "H" },
		{ name: "吉林", id: 234, type: "J" },
		{ name: "江苏", id: 255, type: "J" },
		{ name: "江西", id: 279, type: "J" },
		{ name: "辽宁", id: 294, type: "L" },
		{ name: "内蒙古", id: 333, type: "N" },
		{ name: "宁夏", id: 351, type: "N" },
		{ name: "青海", id: 357, type: "Q" },
		{ name: "山东", id: 368, type: "S" },
		{ name: "山西", id: 393, type: "S" },
		{ name: "陕西", id: 406, type: "S" },
		{ name: "上海", id: 417, type: "S" },
		{ name: "四川", id: 438, type: "S" },
		{ name: "天津", id: 461, type: "T" },
		{ name: "云南", id: 488, type: "Y" },
		{ name: "浙江", id: 508, type: "Z" },
	],
	cityOptionsTwo: [
		{ name: "西藏", id: 463, type: "X" },
		{ name: "新疆", id: 471, type: "X" },
		{ name: "香港", id: 599, type: "X" },
		{ name: "澳门", id: 576, type: "A" },
		{ name: "台湾", id: 577, type: "T" },
		{ name: "中国其它", id: 531, type: "OR" },
	],
	tradeType: {
		ALL: {
			value: "9",
			description: "全部",
		},
		TRIAL: {
			value: "3",
			description: "试用",
		},
		RECHARGE: {
			value: "0",
			description: "充值",
		},
		CONSUME: {
			value: "1",
			description: "消费",
		},
	},
};
