export default {
  commonCons: {
    concatPhone: "0571-28121477",
    accessTokenURI: "https://fuwu.taobao.com/ser/detail.htm?spm=a1z13.8114210.1234-fwlb.4.66875acaKnTDe5&service_code=FW_GOODS-1000967279&tracelog=search&from_key=%E9%92%BB%E5%8C%A0",
    ZSURI: "https: // zuanshi.taobao.com/",
    MinBudget: 300,
    dmpURI: "//dmp.taobao.com/",
    fileUrl: "/zuanjiang/adboard/transfile",
  },
  reg: {
    regPhone: /^0?(13[0-9]|14[57]|15[0-9]|166|17[0-9]|18[0-9]|19[89])[0-9]{8}$/,
    regPhoneCode: /^[0-9]{6}$/,
    regNumber: /^[0-9]+$/,
    regTwoDecimal: /^(([1-9][0-9]*)|(([0]\.\d{1,2}|[1-9][0-9]*\.\d{1,2})))$/,
    regName: /^[\u4E00-\u9FA5]{2,4}$/,
    regEmail: /^[a-zA-Z0-9_.-]+@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.[a-zA-Z0-9]{2,6}$/,
  },
  phoneCode: {
    time: 60,
    btnStartText: "获取验证码",
    btnEndText: "重新发送",
  },
  userStatus: {
    initial: "0000", // 初始化
    normal: "1001", // 正常
    emphone: "5001", // 预算未填
    emintention: "5002", // 店铺未填
    emplat: "5003", // 达摩盘
    readyData: "4002", // 准备数据
  },
  planStatus: {
    start: "8", // 投放
    starting: "0", // 9 投放中
    suspend: "1", // 暂停
    suspending: "8", // 8 暂停中
    resuming: "2", // 2 恢复中
    end: "99",
    init: "9",
  },
  cityFormat: [109, 165, 184, 212, 417, 438],
  cityOptionsOne: [
    { name: "安徽", id: 1, type: "A" },
    { name: "北京", id: 19, type: "B" },
    { name: "重庆", id: 532, type: "C" },
    { name: "福建", id: 39, type: "F" },
    { name: "甘肃", id: 52, type: "G" },
    { name: "广东", id: 68, type: "G" },
    { name: "广西", id: 92, type: "G" },
    { name: "贵州", id: 109, type: "G" },
    { name: "海南", id: 120, type: "H" },
    { name: "河北", id: 125, type: "H" },
    { name: "河南", id: 145, type: "H" },
    { name: "黑龙江", id: 165, type: "H" },
    { name: "湖北", id: 184, type: "H" },
    { name: "湖南", id: 212, type: "H" },
    { name: "吉林", id: 234, type: "J" },
    { name: "江苏", id: 255, type: "J" },
    { name: "江西", id: 279, type: "J" },
    { name: "辽宁", id: 294, type: "L" },
    { name: "内蒙古", id: 333, type: "N" },
    { name: "宁夏", id: 351, type: "N" },
    { name: "青海", id: 357, type: "Q" },
    { name: "山东", id: 368, type: "S" },
    { name: "山西", id: 393, type: "S" },
    { name: "陕西", id: 406, type: "S" },
    { name: "上海", id: 417, type: "S" },
    { name: "四川", id: 438, type: "S" },
    { name: "天津", id: 461, type: "T" },
    { name: "云南", id: 488, type: "Y" },
    { name: "浙江", id: 508, type: "Z" },
  ],
  cityOptionsTwo: [
    { name: "西藏", id: 463, type: "X" },
    { name: "新疆", id: 471, type: "X" },
    { name: "香港", id: 599, type: "X" },
    { name: "澳门", id: 576, type: "A" },
    { name: "台湾", id: 577, type: "T" },
    { name: "中国其它", id: 531, type: "OR" },
  ],
  stageList: [
    { id: "1", name: "蓄水", defaultSe: false },
    { id: "2", name: "预热", defaultSe: true },
    { id: "3", name: "活动", defaultSe: true },
    { id: "4", name: "余热", defaultSe: false },
  ],
  stageckList: ["2", "3"],
  monitoringGroup: [
    {
      name: "投放来源",
      value: "targetSource",
      open: true,
      child: [],
      type: "check",
    },
    {
      name: "付费方式",
      value: "campaignTypeName",
      open: false,
      child: [],
      type: "check",
    },
    {
      name: "人群类型",
      value: "crowdTypeName",
      open: false,
      child: [],
      type: "check",
    },
    {
      name: "投放设备",
      value: "terminalName",
      open: false,
      child: [],
      type: "check",
    },
    {
      name: "流量来源",
      value: "insideName",
      open: false,
      child: [],
      type: "check",
    },
    {
      name: "计划、单元",
      value: "targetSource6",
      open: true,
      child: [
        {
          nameCh: "计划",
          valueCh: "campaignName",
        },
        {
          nameCh: "计划x单元",
          valueCh: "campaignName,transName",
        },
      ],
      type: "radio",
      model: "campaignName,transName",
    },
    {
      name: "创意空间",
      value: "targetSource8",
      open: false,
      child: [
        {
          nameCh: "链接类型",
          valueCh: "space0",
        },
        {
          nameCh: "宝贝及型号",
          valueCh: "space1",
        },
        {
          nameCh: "链接类型x宝贝及型号",
          valueCh: "spaceName",
        },
      ],
      type: "radio",
      model: "",
    },
    {
      name: "业务类型",
      value: "targetSource7",
      open: true,
      child: [
        {
          nameCh: "定向",
          valueCh: "targetName",
        },
        {
          nameCh: "资源位",
          valueCh: "adzoneName",
        },
        {
          nameCh: "创意",
          valueCh: "adboardName",
        },
        {
          nameCh: "定向x资源位",
          valueCh: "adzoneName,targetName",
        },
      ],
      type: "radio",
      model: "targetName",
    },
  ],
  monitoringList: [
    {
      name: "消耗(¥)",
      url: require("../assets/images/xiaohao.png"),
      value: "234,567",
      selected: true,
      color: "rgba(249,161,0,0.1)",
      linecolor: "#F9A100",
      lable: "chargeStr",
      series: "charge",
      formatter: "{value} ¥",
      list: [],
    },
    {
      name: "点击",
      url: require("../assets/images/dianji.png"),
      value: "234,567",
      selected: false,
      color: "rgba(29,207,95,0.1)",
      linecolor: "#1DCF5F",
      lable: "clickStr",
      series: "click",
      formatter: "{value}",
      list: [],
    },
    {
      name: "展现",
      url: require("../assets/images/zhanxian.png"),
      value: "234,567",
      selected: false,
      color: "rgba(28,173,251,0.1)",
      linecolor: "#1CADFB",
      lable: "pvStr",
      series: "pv",
      formatter: "{value}",
      list: [],
    },
    {
      name: "CPC(¥)",
      url: require("../assets/images/cpc.png"),
      value: "234,567",
      selected: true,
      color: "rgba(255,101,42,0.1)",
      linecolor: "rgba(255,101,42,1)",
      lable: "cpcStr",
      series: "cpc",
      formatter: "{value} ¥",
      list: [],
    },
    {
      name: "CPM(¥)",
      url: require("../assets/images/cpm.png"),
      value: "234,567",
      selected: false,
      color: "rgba(71,104,255,0.1)",
      linecolor: "rgba(71,104,255,1)",
      lable: "cpmStr",
      series: "cpm",
      formatter: "{value} ¥",
      list: [],
    },
    {
      name: "CTR(%)",
      url: require("../assets/images/ctr.png"),
      value: "234,567",
      selected: false,
      color: "rgba(199,54,255,0.1)",
      linecolor: "#C736FF",
      lable: "ctrStr",
      series: "ctr",
      formatter: "{value} %",
      list: [],
    },
  ],
  goalList: [
    {
      id: "1Q",
      goalName: "拉新",
      goalOp: "<",
      maxValue: "1",
      minValue: "10",
    },
    {
      id: "2Q",
      goalName: "转化",
      goalOp: "<",
      maxValue: "1",
      minValue: "10",
    },
  ],
  // 基础
  originalAcList: [
    {
      name: "收藏宝贝数",
      type: "inShopItemColNumStr",
      value: "inShopItemColNum",
      checked: false,
      progress: "inShopItemColNumRunk",
    },
    {
      name: "收藏店铺数",
      type: "dirShopColNumStr",
      value: "dirShopColNum",
      checked: false,
      progress: "dirShopColNumRunk",
    },
    {
      name: "加购量",
      type: "cartNumStr",
      value: "cartNum",
      checked: false,
      progress: "cartNumRunk",
    },
    {
      name: "拍下订单量",
      type: "gmvInShopNumStr",
      value: "gmvInShopNum",
      checked: false,
      progress: "gmvInShopNumRunk",
    },
    {
      name: "拍下订单金额(￥)",
      type: "gmvInShopAmtStr",
      value: "gmvInShopAmt",
      checked: false,
      progress: "gmvInShopAmtRunk",
    },
    {
      name: "成交订单数",
      type: "alipayInShopNumStr",
      value: "alipayInShopNum",
      checked: false,
      progress: "alipayInShopNumRunk",
    },
    {
      name: "访客",
      type: "uvStr",
      value: "uv",
      checked: false,
      progress: "uvRunk",
    },
    {
      name: "点击转化率(%)",
      type: "cvrStr",
      value: "cvr",
      checked: false,
      progress: "cvrRunk",
    },
  ],
  // 定向、创意报表
  originalRepCol: [
    {
      name: "收藏宝贝数",
      type: "inShopItemColNumStr",
      value: "inShopItemColNum",
      checked: false,
      progress: "inShopItemColNumRunk",
    },
    {
      name: "收藏店铺数",
      type: "dirShopColNumStr",
      value: "dirShopColNum",
      checked: false,
      progress: "dirShopColNumRunk",
    },
    {
      name: "加购量",
      type: "cartNumStr",
      value: "cartNum",
      checked: false,
      progress: "cartNumRunk",
    },
    {
      name: "拍下订单量",
      type: "gmvInShopNumStr",
      value: "gmvInShopNum",
      checked: false,
      progress: "gmvInShopNumRunk",
    },
    {
      name: "拍下订单金额(￥)",
      type: "gmvInShopAmtStr",
      value: "gmvInShopAmt",
      checked: false,
      progress: "gmvInShopAmtRunk",
    },
    {
      name: "成交订单数",
      type: "alipayInShopNumStr",
      value: "alipayInShopNum",
      checked: false,
      progress: "alipayInShopNumRunk",
    },
    {
      name: "访客",
      type: "uvStr",
      value: "uv",
      checked: false,
      progress: "uvRunk",
    },
    {
      name: "点击转化率(%)",
      type: "cvrStr",
      value: "cvr",
      checked: false,
      progress: "cvrRunk",
    },
  ],
  // 加工
  processAcList: [
    {
      name: "单个访客价值(￥)",
      type: "uvPrimeCostStr",
      value: "uvPrimeCost",
      checked: false,
      progress: "uvPrimeCostRunk",
    },
    {
      name: "展现效率(%)",
      type: "uvPvStr",
      value: "uvPv",
      checked: false,
      progress: "uvPvRunk",
    },
    {
      name: "宝贝收藏成本(￥)",
      type: "itemColCostStr",
      value: "itemColCost",
      checked: false,
      progress: "itemColCostRunk",
    },
    {
      name: "店铺收藏成本(￥)",
      type: "shopColCostStr",
      value: "shopColCost",
      checked: false,
      progress: "shopColCostRunk",
    },
    {
      name: "加购成本(￥)",
      type: "cartPrimeCostStr",
      value: "cartPrimeCost",
      checked: false,
      progress: "cartPrimeCostRunk",
    },
    {
      name: "订单成交率(%)",
      type: "alipayGmvStr",
      value: "alipayGmv",
      checked: false,
      progress: "alipayGmvRunk",
    },
    {
      name: "千次展现收益(￥)",
      type: "pvInStr",
      value: "pvIn",
      checked: false,
      progress: "pvInRunk",
    },
    {
      name: "单次点击价值(￥)",
      type: "clickInStr",
      value: "clickIn",
      checked: false,
      progress: "clickInRunk",
    },
    {
      name: "收藏率(%)",
      type: "dirRateStr",
      value: "dirRate",
      checked: false,
      progress: "dirRateRunk",
    },
    {
      name: "加购率(%)",
      type: "cartRateStr",
      value: "cartRate",
      checked: false,
      progress: "cartRateRunk",
    },
    {
      name: "拍下成交率(%)",
      type: "gmvInRateStr",
      value: "gmvInRate",
      checked: false,
      progress: "gmvInRateRunk",
    },
  ],
  moniAcList: [
    {
      name: "消耗(￥)",
      type: "charge",
      progress: "chargeRunk",
      typeFormat: "chargeStr",
    },
    {
      name: "点击",
      type: "click",
      progress: "clickRunk",
      typeFormat: "clickStr",
    },
    {
      name: "展现",
      type: "pv",
      progress: "pvRunk",
      typeFormat: "pvStr",
    },
    {
      name: "CPC(￥)",
      type: "cpc",
      progress: "cpcRunk",
      checked: false,
      typeFormat: "cpcStr",
    },
    {
      name: "CPM(￥)",
      type: "cpm",
      progress: "cpmRunk",
      checked: false,
      typeFormat: "cpmStr",
    },
    {
      name: "CTR(%)",
      type: "ctr",
      progress: "ctrRunk",
      checked: false,
      typeFormat: "ctrStr",
    },
  ],
  activeEffective: [
    {
      value: "9",
      label: "所有",
    },
    {
      value: "0",
      label: "即将生效",
    },
    {
      value: "1",
      label: "生效",
    },
    {
      value: "2",
      label: "失效",
    },
  ],
  crowdTypes: [
    {
      value: "1",
      name: "广泛拉新",
      type: "aware",
      budget: 300,
      crowdPackType: "1",
    },
    {
      value: "2",
      name: "类目拉新",
      type: "aware",
      budget: 300,
      crowdPackType: "1",
    },
    {
      value: "4",
      name: "竞品拉新",
      type: "aware",
      budget: 300,
      crowdPackType: "1",
    },
    {
      value: "8",
      name: "认知用户",
      type: "aware",
      budget: 300,
      crowdPackType: "1",
    },
    {
      value: "16",
      name: "兴趣用户",
      type: "aware",
      budget: 300,
      crowdPackType: "1",
    },
    {
      value: "32",
      name: "成交用户",
      type: "aware",
      budget: 300,
      crowdPackType: "1",
    },
  ],
  defaultRepCol: [
    {
      name: "投资回报率",
      type: "roi",
      value: "roi",
      typeFormat: "roiStr",
    },
    {
      name: "消耗(￥)",
      type: "charge",
      value: "charge",
      typeFormat: "chargeStr",
    },
    {
      name: "点击",
      type: "click",
      value: "click",
      typeFormat: "clickStr",
    },
    {
      name: "展现",
      type: "pv",
      value: "pv",
      typeFormat: "pvStr",
    },
  ],
  headerDefRep: [
    {
      name: "消耗(￥)",
      type: "chargeStr",
    },
    {
      name: "点击",
      type: "clickStr",
    },
    {
      name: "展现",
      type: "pvStr",
    },
    {
      name: "CPM(￥)",
      type: "cpmStr",
    },
    {
      name: "CPC(￥)",
      type: "cpcStr",
    },
    {
      name: "CTR(%)",
      type: "ctrStr",
    },
    {
      name: "收藏宝贝数",
      type: "inShopItemColNumStr",
    },
    {
      name: "收藏店铺数",
      type: "dirShopColNumStr",
    },
    {
      name: "加购量",
      type: "cartNumStr",
    },
    {
      name: "拍下订单量",
      type: "gmvInShopNumStr",
    },
    {
      name: "拍下订单金额(￥)",
      type: "gmvInShopAmtStr",
    },
    {
      name: "成交订单数",
      type: "alipayInShopNumStr",
    },
    {
      name: "成交订单金额(￥)",
      type: "alipayInShopAmtStr",
    },
    {
      name: "访客",
      type: "uvStr",
    },
    {
      name: "点击转化率(%)",
      type: "cvrStr",
    },
    {
      name: "投资回报率",
      type: "roiStr",
    },
    {
      name: "单个访客价值(￥)",
      type: "uvPrimeCostStr",
    },
    {
      name: "展现效率(%)",
      type: "uvPvStr",
    },
    {
      name: "宝贝收藏成本(￥)",
      type: "itemColCostStr",
    },
    {
      name: "店铺收藏成本(￥)",
      type: "shopColCostStr",
    },
    {
      name: "加购成本(￥)",
      type: "cartPrimeCostStr",
    },
    {
      name: "订单成交率(%)",
      type: "alipayGmvStr",
    },
    {
      name: "千次展现收益(￥)",
      type: "pvInStr",
    },
    {
      name: "单次点击价值(￥)",
      type: "clickInStr",
    },
    {
      name: "收藏率(%)",
      type: "dirRateStr",
    },
    {
      name: "加购率(%)",
      type: "cartRateStr",
    },
    {
      name: "拍下成交率(%)",
      type: "gmvInRateStr",
    },
  ],
  arrCrowdType: [1, 2, 4, 8, 16, 32],
  accurateCrowds: [
    {
      name: "过滤购买人群",
      value: "1",
      desc: "过滤掉在店铺内产生购买的人群（不区分自然流量和广告流量）",
      list: [
        { name: "7天", value: "7" },
        { name: "15天", value: "15" },
        { name: "30天", value: "30" },
      ],
    },
    {
      name: "过滤加购人群",
      value: "2",
      desc: "过滤掉在店铺内产生加购的人群（不区分自然流量和广告流量）",
      list: [
        { name: "7天", value: "7" },
        { name: "15天", value: "15" },
      ],
    },
    {
      name: "过滤收藏人群",
      value: "3",
      desc: "过滤掉在店铺内产生收藏的人群（不区分自然流量和广告流量）",
      list: [
        { name: "7天", value: "7" },
        { name: "15天", value: "15" },
      ],
    },
    {
      name: "过滤进店人群",
      value: "4",
      desc: "过滤掉产生进店的人群（不区分自然流量和广告流量，包括店铺首页及店铺宝贝详情页）",
      list: [{ name: "7天", value: "7" }],
    },
  ],
};
